services:
  xlink-kai:
    container_name: xlink-kai
    image: macgyverbass/xlink-kai:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - '/home/docker/xlink-data:/root/.xlink/'

  egl:
    container_name: egl
    hostname: egl
    # Change tag 'latest' to Ubuntu versions such as '24.04', use a persistent tag such as '24.04-20210101010101' to persist a certain container version
    image: ghcr.io/selkies-project/nvidia-egl-desktop:latest
    # Port mappings are ignored when using host network mode, but kept for documentation
    ports:
      - '8080:8080'
      - '3074:3074'
      - '34522:34522'
      - '34523:34523'
      - '30000:30000'
      # Internal TURN server settings
      # - '3478:3478'
      # - '65534-65535:65534-65535'
      # - '3478:3478/udp'
      # - '65534-65535:65534-65535/udp'
    stdin_open: true
    tty: true
    # Removed GPU reservation section for CPU-only system
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: 1
    #         capabilities: [gpu]
    tmpfs:
      - '/dev/shm:rw'
    # Persistent data volumes with host directory mapping
    volumes:
      - '/home/docker/egl-data/cache:/cache'
      - '/home/docker/egl-data/home:/home/ubuntu'
    cap_add:
      - NET_ADMIN

    # Enable host networking mode for direct access to host's network interfaces
    network_mode: 'host'

    # Resource limits removed for unlimited resource usage
    environment:
      - TZ=UTC
      # Reduced resolution for better CPU performance
      - DISPLAY_SIZEW=1280
      - DISPLAY_SIZEH=720
      - DISPLAY_REFRESH=30
      - DISPLAY_DPI=96
      - DISPLAY_CDEPTH=24
      # Keep to default unless you know what you are doing with VirtualGL, `VGL_DISPLAY` should be set to either `egl[n]` or `/dev/dri/card[n]` only when the device was passed to the container
      # - VGL_DISPLAY=egl
      # User password of container - change this to a secure password
      - PASSWD=H@lo2Rocks@@@
      # Uncomment to enable KasmVNC instead of Selkies-GStreamer, `SELKIES_BASIC_AUTH_PASSWORD` is used for authentication with KasmVNC, defaulting to `PASSWD` if not provided
      # Uses: `SELKIES_ENABLE_BASIC_AUTH`, `SELKIES_BASIC_AUTH_USER`, `SELKIES_BASIC_AUTH_PASSWORD`, `SELKIES_ENABLE_RESIZE`, `SELKIES_ENABLE_HTTPS`, `SELKIES_HTTPS_CERT`, `SELKIES_HTTPS_KEY`
      # - KASMVNC_ENABLE=true
      # Number of threads for encoding frames with KasmVNC, default value is all threads
      # - KASMVNC_THREADS=0
      # Selkies-GStreamer parameters, for additional configurations see `selkies-gstreamer --help`
      # Changed encoder to x264enc for CPU-only systems
      - SELKIES_ENCODER=x264enc
      - SELKIES_ENABLE_RESIZE=false
      # Reduced bitrate for better CPU performance
      - SELKIES_VIDEO_BITRATE=4000
      # Reduced framerate for better CPU performance
      - SELKIES_FRAMERATE=30
      - SELKIES_AUDIO_BITRATE=128000
      # Added software rendering flag for CPU-only systems
      - SELKIES_SOFTWARE_RENDERING=true
      # Uncomment if network conditions rapidly fluctuate
      # - SELKIES_CONGESTION_CONTROL=true
      # Enable Basic Authentication from the web interface
      - SELKIES_ENABLE_BASIC_AUTH=true
      # Defaults to `PASSWD` if unspecified
      # - SELKIES_BASIC_AUTH_PASSWORD=mypasswd
      # Enable HTTPS web interface from inside the container
      - SELKIES_ENABLE_HTTPS=false
      # Volume mount trusted HTTPS certificate to new path for no web browser warnings
      # - SELKIES_HTTPS_CERT=/etc/ssl/certs/ssl-cert-snakeoil.pem
      # - SELKIES_HTTPS_KEY=/etc/ssl/private/ssl-cert-snakeoil.key
      # Uncomment and configure below to use a TURN server for improved network compatibility
      # - SELKIES_TURN_HOST=turn.example.com
      # - SELKIES_TURN_PORT=3478
      # Change to `tcp` if the UDP protocol is throttled or blocked in your client network, or when the TURN server does not support UDP
      # - SELKIES_TURN_PROTOCOL=udp
      # You need a valid hostname and a certificate from authorities such as ZeroSSL or Let's Encrypt with your TURN server to enable TURN over TLS
      # - SELKIES_TURN_TLS=false
      # Internal TURN server settings, do not uncomment other TURN server settings below this when using an internal TURN server
      # - TURN_MIN_PORT=65534
      # - TURN_MAX_PORT=65535
      # Provide only `SELKIES_TURN_SHARED_SECRET` for time-limited shared secret authentication or both `SELKIES_TURN_USERNAME` and `SELKIES_TURN_PASSWORD` for legacy long-term authentication, but do not provide both authentication methods at the same time
      # - SELKIES_TURN_SHARED_SECRET=n0TaRealCoTURNAuthSecretThatIsSixtyFourLengthsLongPlaceholdPlace
      # - SELKIES_TURN_USERNAME=username
      # - SELKIES_TURN_PASSWORD=mypasswd
      # TURN REST URI authentication, all TURN server settings above are ignored if enabled
      # - SELKIES_TURN_REST_URI=http://localhost:8008

