[general]
show_welcome = false
skip_boot_anim = true

[general.snapshots.shortcuts]
f6 = 'available games lobby'

[input.bindings]
port1 = 'keyboard'

[display.window]
startup_size = '640x480'
last_width = 1280
last_height = 648
vsync = false

[display.ui]
use_animations = false

[display.debug.video]
transparency = true
x_pos = 13
y_pos = 351

[audio]
hrtf = false
volume_limit = 0.108755

[net]
enable = true
backend = 'udp'

[net.udp]
bind_addr = '0.0.0.0:9968'
remote_addr = '127.0.0.1:34523'

[sys.files]
bootrom_path = '/home/ubuntu/Desktop/xemu/mcpx_1.0.bin'
flashrom_path = '/home/ubuntu/Desktop/xemu/complex_4627.bin'
eeprom_path = '/home/ubuntu/Desktop/xemu/eeprom.bin'
hdd_path = '/home/ubuntu/Desktop/xemu/xbox_hdd.qcow2'
dvd_path = '/home/ubuntu/Desktop/xemu/halo2_r1e_xiso.iso'

